-- =============================================================================
-- GCentreFormation — MPD Oracle (XE 11g / 12c+)
-- Modules : FORMATEUR + COURS
-- A executer dans SQL Developer en tant qu'utilisateur du projet (ex. cpp)
-- =============================================================================

-- Nettoyage (ignore les erreurs si les objets n'existent pas)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COURS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FORMATEUR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FORMATEUR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COURS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FORMATEUR_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_COURS_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_FORMATEUR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COURS START WITH 1 INCREMENT BY 1 NOCACHE;

-- -----------------------------------------------------------------------------
-- FORMATEUR
-- -----------------------------------------------------------------------------
CREATE TABLE FORMATEUR (
    ID_FORMATEUR    NUMBER          NOT NULL,
    CIN             VARCHAR2(8)     NOT NULL,
    NOM             VARCHAR2(50)    NOT NULL,
    PRENOM          VARCHAR2(50)    NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL,
    TELEPHONE       VARCHAR2(8)     NOT NULL,
    SPECIALITE      VARCHAR2(50)    NOT NULL,
    DATE_EMBAUCHE   DATE            NOT NULL,
    STATUT          VARCHAR2(20)    DEFAULT 'Actif' NOT NULL,
    CONSTRAINT PK_FORMATEUR PRIMARY KEY (ID_FORMATEUR),
    CONSTRAINT UQ_FORMATEUR_CIN UNIQUE (CIN),
    CONSTRAINT UQ_FORMATEUR_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_FORM_CIN CHECK (REGEXP_LIKE(CIN, '^[0-9]{8}$')),
    CONSTRAINT CHK_FORM_TEL CHECK (REGEXP_LIKE(TELEPHONE, '^[0-9]{8}$')),
    CONSTRAINT CHK_FORM_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CHK_FORM_NOM CHECK (LENGTH(TRIM(NOM)) >= 2),
    CONSTRAINT CHK_FORM_PRENOM CHECK (LENGTH(TRIM(PRENOM)) >= 2),
    CONSTRAINT CHK_FORM_STATUT CHECK (STATUT IN ('Actif', 'Inactif'))
);

CREATE OR REPLACE TRIGGER TRG_FORMATEUR_BI
BEFORE INSERT ON FORMATEUR
FOR EACH ROW
BEGIN
    IF :NEW.ID_FORMATEUR IS NULL THEN
        SELECT SEQ_FORMATEUR.NEXTVAL INTO :NEW.ID_FORMATEUR FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- COURS  (un cours a exactement un formateur)
-- -----------------------------------------------------------------------------
CREATE TABLE COURS (
    ID_COURS        NUMBER          NOT NULL,
    TITRE           VARCHAR2(100)   NOT NULL,
    NIVEAU          VARCHAR2(20)    NOT NULL,
    DUREE_H         NUMBER          NOT NULL,
    PRIX            NUMBER(10,2)    NOT NULL,
    DATE_DEBUT      DATE            NOT NULL,
    DATE_FIN        DATE            NOT NULL,
    STATUT          VARCHAR2(20)    DEFAULT 'Planifie' NOT NULL,
    ID_FORMATEUR    NUMBER          NOT NULL,
    CONSTRAINT PK_COURS PRIMARY KEY (ID_COURS),
    -- Oracle : pas de ON DELETE RESTRICT (syntaxe invalide).
    -- Sans clause ON DELETE = comportement restrict (ORA-02292 si formateur a des cours).
    CONSTRAINT FK_COURS_FORMATEUR FOREIGN KEY (ID_FORMATEUR)
        REFERENCES FORMATEUR (ID_FORMATEUR),
    CONSTRAINT CHK_COURS_TITRE CHECK (LENGTH(TRIM(TITRE)) >= 3),
    CONSTRAINT CHK_COURS_NIVEAU CHECK (NIVEAU IN ('Debutant', 'Intermediaire', 'Avance')),
    CONSTRAINT CHK_COURS_STATUT CHECK (STATUT IN ('Planifie', 'En cours', 'Termine', 'Annule')),
    CONSTRAINT CHK_COURS_DUREE CHECK (DUREE_H > 0),
    CONSTRAINT CHK_COURS_PRIX CHECK (PRIX > 0),
    CONSTRAINT CHK_COURS_DATES CHECK (DATE_FIN >= DATE_DEBUT)
);

CREATE OR REPLACE TRIGGER TRG_COURS_BI
BEFORE INSERT ON COURS
FOR EACH ROW
BEGIN
    IF :NEW.ID_COURS IS NULL THEN
        SELECT SEQ_COURS.NEXTVAL INTO :NEW.ID_COURS FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_COURS_FORMATEUR ON COURS (ID_FORMATEUR);
CREATE INDEX IDX_COURS_STATUT ON COURS (STATUT);
CREATE INDEX IDX_FORM_SPECIALITE ON FORMATEUR (SPECIALITE);
CREATE INDEX IDX_FORM_STATUT ON FORMATEUR (STATUT);

-- -----------------------------------------------------------------------------
-- Jeu d'essai (statistiques et graphiques lisibles)
-- -----------------------------------------------------------------------------
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('12345678', 'Ben Ali', 'Sami', 'sami.benali@forma.tn', '98111222', 'Informatique', DATE '2021-09-01', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('22345678', 'Trabelsi', 'Ines', 'ines.trabelsi@forma.tn', '98333444', 'Reseaux', DATE '2022-01-15', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('32345678', 'Gharbi', 'Omar', 'omar.gharbi@forma.tn', '98555666', 'Cybersecurite', DATE '2020-03-10', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('42345678', 'Mansouri', 'Lina', 'lina.mansouri@forma.tn', '98777888', 'Gestion', DATE '2023-02-01', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('52345678', 'Jebali', 'Karim', 'karim.jebali@forma.tn', '98999000', 'Informatique', DATE '2019-11-20', 'Inactif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('62345678', 'Hammami', 'Sara', 'sara.hammami@forma.tn', '97111222', 'Langues', DATE '2024-01-08', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('72345678', 'Bouazizi', 'Hedi', 'hedi.bouazizi@forma.tn', '97333444', 'Intelligence Artificielle', DATE '2022-06-12', 'Actif');
INSERT INTO FORMATEUR (CIN, NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUT)
VALUES ('82345678', 'Karray', 'Nour', 'nour.karray@forma.tn', '97555666', 'Reseaux', DATE '2021-04-18', 'Actif');

INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('C++ Orienter Objet', 'Debutant', 30, 450, DATE '2026-09-08', DATE '2026-09-26', 'Planifie', 1);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Qt Desktop Avance', 'Avance', 40, 720, DATE '2026-10-05', DATE '2026-10-30', 'Planifie', 1);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Administration Reseaux', 'Intermediaire', 35, 600, DATE '2026-09-14', DATE '2026-10-02', 'Planifie', 2);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Securite des SI', 'Avance', 28, 800, DATE '2026-08-01', DATE '2026-08-20', 'Termine', 3);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Ethical Hacking', 'Avance', 32, 850, DATE '2026-09-10', DATE '2026-09-28', 'Planifie', 3);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Gestion de Projet', 'Debutant', 20, 380, DATE '2026-09-01', DATE '2026-09-12', 'En cours', 4);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Anglais Professionnel', 'Debutant', 24, 320, DATE '2026-11-02', DATE '2026-11-20', 'Planifie', 6);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Machine Learning', 'Intermediaire', 36, 900, DATE '2026-10-12', DATE '2026-11-06', 'Planifie', 7);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Deep Learning', 'Avance', 40, 980, DATE '2026-10-15', DATE '2026-11-10', 'Planifie', 7);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Cisco CCNA', 'Intermediaire', 45, 750, DATE '2026-09-21', DATE '2026-10-16', 'Planifie', 8);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Introduction SQL', 'Debutant', 18, 290, DATE '2026-07-01', DATE '2026-07-12', 'Termine', 1);
INSERT INTO COURS (TITRE, NIVEAU, DUREE_H, PRIX, DATE_DEBUT, DATE_FIN, STATUT, ID_FORMATEUR)
VALUES ('Python Data', 'Intermediaire', 30, 540, DATE '2026-09-07', DATE '2026-09-25', 'Annule', 5);

COMMIT;
